
stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: node:10
  only:
    - main
  script:
    - echo "Ejecutando build "
    - cd Frontend/auto-app
    - rm ./package-lock.json
    - npm cache clear --force
    - npm install --force
    - npm run build
  artifacts:
    paths:
      - build
  
test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: node:10
  only:
    - main
  before_script:
    - echo "Running unit tests... This will take about 60 seconds."
  script:
    - cd Frontend/auto-app
    

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  only: 
    - main
  script:
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp build s3://$S3_BUCKET --recursive
